export const HOST = {
  me: "auth/me",
  login: "auth/token",
  download: "download",
  refresh: "auth/refresh-token",
  register: "auth/register",
  generate: "generate",
  editImage: "generate/edit",
  editURLImage: "generate/edit-from-url",
  batchEditImage: "generate/batch-edit",
  history: "generate/history",
  deleteHistory: "generate/history",
  upload: "upload",
  uploadToLeonardo: "generate/upload-to-leonardo",
  uploadVideo: "upload-video",
  generateVideo: "generate/video",
  generateTextToVideo: "generate/text-to-video",
  promptGenerating: "picture-ads/prompt-generating",
  pictureAdsGenerate: "picture-ads/edit",
  pictureAdsMergeGenerate: "picture-ads/edit-merge",
  upscaleImage: "picture-ads/upscale-from-gcs",
  upscaleVariation: "picture-ads/upscale/variations",
};
