export const HOST = {
  me: "auth/me",
  login: "auth/token",
  refresh: "auth/refresh-token",
  register: "auth/register",
  generate: "generate",
  editImage: "generate/edit",
  editURLImage: "generate/edit-from-url",
  batchEditImage: "generate/batch-edit",
  history: "generate/history",
  deleteHistory: "generate/history",
  upload: "upload",
  uploadVideo: "upload-video",
  generateVideo: "generate/video",
  generateTextToVideo: "generate/text-to-video",
  promptGenerating: "picture-ads/prompt-generating",
};
